version: '3'
services:
  kronos-test:
    build:
      context: ""
      dockerfile: dockerfile/kronos-test.dockerfile
    image: kronos-test:latest
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      WAIT_HOSTS: db-test-mysql:3306
    depends_on:
      db-test-postgres:
        condition: service_healthy
      db-test-mysql:
        condition: service_healthy
  db-test-postgres:
    restart: always
    image: postgres:alpine
    ports:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  db-test-mysql:
    image: mysql:5.7.31
    restart: always
    ports:
     - "3306"
    healthcheck:
      test: ["CMD-SHELL", "/etc/init.d/mysql status"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./test_config/init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password